import javafx.scene.control.Alert;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

/**
 * This is a multi-threaded class that handles the connection objects passed to it by the server listener.
 * This class accepts information from the client and passes back updated information for other players
 *
 * Bugs: None known
 * @author Luke Hanna (Github.com/JustAPyro)
 * @date Feb 15, 2021
 * @version 1.0
 */
public class ServerThread extends Thread
{

    private ObjectOutputStream outStream; // This will be used to write to client
    private ObjectInputStream inStream; // This will be used to read from client

    /**
     * Main constructor initializes a server thread that will manage one client connection
     *
     * @param connection The TCP connection with the client generated by ServerListener
     */
    public ServerThread(Socket connection)
    {
        try {
            // Get the IO Data streams from client TCP connection
            outStream = new ObjectOutputStream(connection.getOutputStream());
            inStream = new ObjectInputStream(connection.getInputStream());
        }
        catch (IOException e) // Couldn't get data stream from client connection
        {
            // Inform the user
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("ERROR");
            alert.setHeaderText("Fatal Error: Could not get IO Streams from Client");
            alert.show();
            return;
        }
    }

    /**
     * This is the overridden method that runs on a different thread- This starts running when start() is called by ServerListener
     * @Override
     */
    public void run()
    {
        // This runs an infinite loop managing the TCP connection with the client
        while (true)
        {
            try
            {
                // This is simply placeholder until a client has been scripted that sends objects
                Object x = inStream.readObject();
                outStream.writeObject("Thanks!");
            }
            catch (IOException | ClassNotFoundException e) // If there was an error reading the object
            {
                // Inform the user
                Alert alert = new Alert(Alert.AlertType.ERROR);
                alert.setTitle("ERROR");
                alert.setHeaderText("Error: Could not read data from client IO stream");
                alert.show();
            }
        }
    }
}
